apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-namespace  # Specify the namespace
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: my-app:latest  # Ensure this matches the image you build
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
