apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: my-namespace  # Specify the namespace
spec:
  type: NodePort  # Change to LoadBalancer if needed
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80  # Exposed port
      targetPort: 8080  # Match with your app's containerPort
