name: Build and Push 4 Docker Images to AWS Public ECR

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build-and-Push-All-Images
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    strategy:
      matrix:
        include:
          - name: cake-backend-apache
            folder: cake-backend-apache
            repository: public.ecr.aws/w7d0i3d5/cake/backend

          - name: cake-frontend-tomcat
            folder: cake-frontend-tomcat
            repository: public.ecr.aws/w7d0i3d5/cake/frontend

          - name: cake-pda-nginx-1
            folder: cake-pda-nginx-1
            repository: public.ecr.aws/w7d0i3d5/cake/pda

          - name: cake-scia-agent-nginx-2
            folder: cake-scia-agent-nginx-2
            repository: public.ecr.aws/w7d0i3d5/cake/scia-agent

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to AWS Public ECR
        run: |
          aws ecr-public get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build Docker Image
        run: |
          docker build -t ${{ matrix.name }} ./${{ matrix.folder }}

      - name: Tag Docker Image
        run: |
          docker tag ${{ matrix.name }}:latest ${{ matrix.repository }}:latest
          docker tag ${{ matrix.name }}:latest ${{ matrix.repository }}:${{ github.run_number }}

      - name: Push Docker Image
        run: |
          docker push ${{ matrix.repository }}:latest
          docker push ${{ matrix.repository }}:${{ github.run_number }}

  deploy:
    name: Deploy-All-Cake-Services
    runs-on: ubuntu-latest
    needs: docker
  
    strategy:
      matrix:
        include:
          - service: cake-backend-service
          - service: cake-frontend-service
          - service: cake-pda-service
          - service: cake-scia-service
  
    env:
      AWS_REGION: us-east-1
      ECS_CLUSTER: my-ecs-cluster
  
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
  
      - name: Force New Deployment
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service ${{ matrix.service }} \
            --force-new-deployment
